

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=welldev
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - 5672:5672
      - 15672:15672

  mailpit:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025